name: girlzwhosell
description: girlzwhosell Career Connexions

publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  webview_flutter: ^3.0.1
  shared_preferences:
  multi_select_flutter:
  pin_input_text_field: ^4.1.1
  flutter_tindercard: ^0.2.0
  favorite_button: ^0.0.4
  path_provider: ^2.0.9
  firebase_messaging:
  firebase_core:
  overlay_support:
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0
  gradient_widgets: ^0.6.0
  dotted_border: ^2.0.0+2
  rflutter_alert: ^2.0.4
  url_launcher: ^6.0.20
  flutter_screenutil: ^5.3.1
  carousel_slider: ^4.0.0
  flutter_svg: ^1.0.3
  animations: ^2.0.2
  dio: ^4.0.5
  file_picker: ^4.4.0
  image_picker:
  email_validator: ^2.0.1
  fluttertoast: ^8.0.7
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2
  animated_text_kit:
  firebase_analytics: ^9.1.1
  flutter_downloader: ^1.7.2
  permission_handler: ^9.0.2
  flutter_styled_toast: ^2.0.0
  animated_splash: ^1.0.0
  lottie:
  badges: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/appIcon.png
    - assets/images/default.jpg
    - assets/images/letters/
    - assets/icons/airbnb_logo.svg
    - assets/icons/apple_logo.svg
    - assets/icons/chevron_left_icon.svg
    - assets/icons/close_icon.svg
    - assets/icons/google_logo.svg
    - assets/icons/heart_icon.svg
    - assets/icons/search.svg
    - assets/icons/slider_icon.svg
    - assets/audio/sound.mp3

  fonts:
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
          weight: 800
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Questrial-Regular.ttf